name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  intl: ^0.19.0
  url_launcher: ^6.1.12
  lottie: ^2.7.0
  connectivity_plus: ^5.0.1
  http: ^1.1.0
  logger: ^2.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.2
  animated_toggle_switch: ^0.8.3
  font_awesome_flutter: ^10.7.0
  flutter_svg_icons: ^0.0.1
  intl_phone_field: ^3.2.0
  mask_text_input_formatter: ^2.9.0

  #Firebase
  firebase_core: any
  firebase_auth: any
  firebase_cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PT Sans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700

    - family: VK Sans
      fonts:
        - asset: assets/fonts/VKSansDisplay-Bold.ttf
          weight: 800
        - asset: assets/fonts/VKSansDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/VKSansDisplay-Regular.ttf
          weight: 400
